#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, List

import pandas as pd

WINDOW_ORDER = ["peak1", "valley", "peak2"]


def _center(tL: int, tR: int) -> int:
    return int(round((tL + tR) / 2))


def _format_sci(val: float) -> str:
    return f"{val:.2e}"


def main() -> None:
    parser = argparse.ArgumentParser(description="Export window parameters and counts table for the report.")
    parser.add_argument("--input-json", required=True, type=Path)
    parser.add_argument("--ft-csv", required=True, type=Path)
    parser.add_argument("--out-csv", required=True, type=Path)
    parser.add_argument("--out-tex", required=True, type=Path)
    parser.add_argument("--out-tex-en", required=False, type=Path, default=None)
    parser.add_argument("--col-t", default="t")
    parser.add_argument("--col-k2", default="f_K2")
    parser.add_argument("--col-k4", default="f_K4")
    args = parser.parse_args()

    data = json.loads(args.input_json.read_text())
    intervals: Dict[str, List[int]] = data["bin_intervals"]
    n_windows = data.get("n_windows", {})

    df = pd.read_csv(args.ft_csv)
    t_to_idx = {int(t): i for i, t in enumerate(df[args.col_t].to_list())}

    rows = []
    for window in WINDOW_ORDER:
        tL, tR = intervals[window]
        center = _center(tL, tR)
        width = int(tR - tL)
        delta = int(round(width / 2))
        idx = t_to_idx.get(center)
        if idx is None:
            raise ValueError(f"t={center} not found in ft-csv t column")
        f_k2 = float(df.loc[idx, args.col_k2]) if args.col_k2 in df.columns else float("nan")
        f_k4 = float(df.loc[idx, args.col_k4]) if args.col_k4 in df.columns else float("nan")
        rows.append(
            {
                "window": window,
                "t_center": center,
                "t_L": tL,
                "t_R": tR,
                "delta": delta,
                "width": width,
                "f_K2": f_k2,
                "f_K4": f_k4,
                "n_K2": int(n_windows.get("K=2", {}).get(window, 0)),
                "n_K4": int(n_windows.get("K=4", {}).get(window, 0)),
            }
        )

    out_df = pd.DataFrame(rows)
    args.out_csv.parent.mkdir(parents=True, exist_ok=True)
    out_df.to_csv(args.out_csv, index=False)

    tex_lines = [
        "% Auto-generated by export_window_table.py",
        "\\begin{table}[!htbp]",
        "\\centering",
        "\\scriptsize",
        "\\setlength{\\tabcolsep}{3pt}",
        "\\caption{窗口参数与样本量（$\\beta=0.01, N=100$；窗口中心来自 $K=4$ 峰谷检测）。}",
        "\\label{tab:window-params}",
        "\\resizebox{\\linewidth}{!}{%",
        "\\begin{tabular}{lrrrrrrrrr}",
        "\\toprule",
        "window & $t_{\\mathrm{center}}$ & $t_L$ & $t_R$ & $\\Delta$ & width & $f_{K=2}(t_c)$ & $f_{K=4}(t_c)$ & $n_{K=2}$ & $n_{K=4}$ \\\\",
        "\\midrule",
    ]
    for row in rows:
        tex_lines.append(
            f"{row['window']} & {row['t_center']} & {row['t_L']} & {row['t_R']} & {row['delta']} & {row['width']} "
            f"& {_format_sci(row['f_K2'])} & {_format_sci(row['f_K4'])} & {row['n_K2']} & {row['n_K4']} \\\\"
        )
    tex_lines += ["\\bottomrule", "\\end{tabular}}", "\\end{table}"]
    args.out_tex.parent.mkdir(parents=True, exist_ok=True)
    args.out_tex.write_text("\n".join(tex_lines) + "\n", encoding="utf-8")

    if args.out_tex_en is not None:
        tex_lines_en = [
            "% Auto-generated by export_window_table.py",
            "\\begin{table}[!htbp]",
            "\\centering",
            "\\scriptsize",
            "\\setlength{\\tabcolsep}{3pt}",
            "\\caption{Window parameters and sample counts ($\\beta=0.01, N=100$; centers from $K=4$ peak/valley detection).}",
            "\\label{tab:window-params-en}",
            "\\resizebox{\\linewidth}{!}{%",
            "\\begin{tabular}{lrrrrrrrrr}",
            "\\toprule",
            "window & $t_{\\mathrm{center}}$ & $t_L$ & $t_R$ & $\\Delta$ & width & $f_{K=2}(t_c)$ & $f_{K=4}(t_c)$ & $n_{K=2}$ & $n_{K=4}$ \\\\",
            "\\midrule",
        ]
        for row in rows:
            tex_lines_en.append(
                f"{row['window']} & {row['t_center']} & {row['t_L']} & {row['t_R']} & {row['delta']} & {row['width']} "
                f"& {_format_sci(row['f_K2'])} & {_format_sci(row['f_K4'])} & {row['n_K2']} & {row['n_K4']} \\\\"
            )
        tex_lines_en += ["\\bottomrule", "\\end{tabular}}", "\\end{table}"]
        args.out_tex_en.parent.mkdir(parents=True, exist_ok=True)
        args.out_tex_en.write_text("\n".join(tex_lines_en) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
